# Generated by Django 4.2.13 on 2024-05-12 17:39

import cacaoApp.utils
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cacaoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 17, 39, 16, 398492, tzinfo=datetime.timezone.utc), verbose_name='fecha'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
