# Generated by Django 4.2.13 on 2024-05-12 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0002_imagemodel_fecha_imagemodel_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 17, 40, 27, 320237, tzinfo=datetime.timezone.utc), verbose_name='fecha'),
        ),
    ]
