# Generated by Django 4.2.13 on 2024-05-12 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cacaoApp', '0003_alter_imagemodel_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='usuario',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
