# Generated by Django 4.2.13 on 2024-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0004_alter_imagemodel_options_remove_imagemodel_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='mazorcaState',
            field=models.CharField(choices=[('Mazorca Saludable', 'Saludable'), ('Mazorca con Monilia', 'Monilia'), ('Mazorca con Phytophthora', 'Phytophthora')], default='Mazorca Saludable', max_length=25),
        ),
    ]
