# Generated by Django 4.2.13 on 2024-05-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0005_imagemodel_mazorcastate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='mazorcaState',
            field=models.CharField(choices=[('Saludable', 'Saludable'), ('Monilia', 'Monilia'), ('Phytophthora', 'Phytophthora')], default='Mazorca Saludable', max_length=25),
        ),
    ]
