# Generated by Django 4.2.13 on 2024-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0006_alter_imagemodel_mazorcastate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='mazorcaState',
            field=models.CharField(max_length=40),
        ),
    ]

