# Generated by Django 4.2.13 on 2024-05-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0007_alter_imagemodel_mazorcastate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='cacaoimages/'),
        ),
    ]
