# Generated by Django 4.2.13 on 2024-05-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0010_alter_imagemodel_mazorcastate'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='healthyPod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='moniliaPod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='pythophoraPod',
            field=models.IntegerField(default=0),
        ),
    ]
