# Generated by Django 4.2.13 on 2024-05-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0012_podcount_remove_imagemodel_healthypod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='mazorcaState',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
