# Generated by Django 4.2.13 on 2024-05-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0013_alter_imagemodel_mazorcastate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='mazorcaState',
            field=models.CharField(default='', max_length=500),
        ),
    ]
