# Generated by Django 4.2.13 on 2024-05-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0015_remove_imagemodel_podcount_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='mazorcaState',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
