# Generated by Django 4.2.13 on 2024-05-27 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0018_fertilizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
