# Generated by Django 4.2.13 on 2024-05-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0020_fertilizer_sciencename'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='linkFertilizer',
            field=models.CharField(default='https://www.amazon.com/', max_length=300),
        ),
    ]
