# Generated by Django 4.2.13 on 2024-05-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0021_fertilizer_linkfertilizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='benefits',
            field=models.TextField(default='Beneficios no especificados'),
        ),
    ]
