# Generated by Django 4.2.13 on 2024-05-28 15:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0022_fertilizer_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='recomendation',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
