# Generated by Django 4.2.13 on 2024-05-28 15:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0023_alter_fertilizer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='recomendation',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=8000),
        ),
    ]
