# Generated by Django 4.2.13 on 2024-05-28 15:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacaoApp', '0024_alter_fertilizer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='benefits',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='recomendation',
            field=models.CharField(max_length=100),
        ),
    ]
